cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/tommaso/OldNS3/ns-allinone-3.17/ns-3.17/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/tommaso/OldNS3/ns-allinone-3.17/ns-3.17/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139672275501392: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-O3\', \'-g\', \'-Wall\', \'-Werror\', \'-march=native\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
